[package]
name = "didcomm-grpc"
version = "0.1.0"
authors = ["Tomislav Markovski <tomislav@trinsic.id>"]
edition = "2018"

[dependencies]
chacha20poly1305 = "0.7.0"
ffi-support = "0.4"
prost = "0.6"
prost-types = "0.6"
base64 = "0.13.0"
hex = "0.4.2"
getrandom = { version = "0.2", features = ["js"] }
regex = "1"
did-key = "0.0.8"
# did-key = { path = "../did-key.rs" }
jni = { version = "0.18" }
serde = "1.0.119"
serde_json = "1.0.60"

[lib]
name = "didcommgrpc"
crate-type = [ "lib", "cdylib", "staticlib" ]

[build-dependencies]
prost-build = "0.6"

[dev-dependencies]
fluid = "0.4"
wasm-bindgen-test = "0.3.13"
bs58 = "0.3.1"
