name: build-libs

on:
  pull_request:
    branches:
      - master

jobs:
  build_windows:
    name: Build for Windows
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run build script
        run: ./devops/Build.ps1 -Platform Windows
        shell: powershell