name: "Web Assembly: Build, Test"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "Package Version"
        required: true
        default: "1.0.0"

jobs:
  build_test:
    name: Build for Web Assembly
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./wasm
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: npm run start
      - run: npm run build
      - run: npm run test

  publish_npm:
    name: Publish packages to NPM
    if: |
      github.event_name == 'release' &&
      github.event.action == 'published' &&
      github.release.draft == false &&
      github.release.prerelease == false
    runs-on: windows-latest
    needs: [build_test]
    defaults:
      run:
        working-directory: ./wasm
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: npm run start
      - run: npm run build
      - name: Generate Package Version
        run: |
          $packageVersion = node -p -e "require('./package.json').version"
          $manualVersion = "${{ github.event.release.tag_name }}"
          $version = if ($manualVersion) { $manualVersion } else { $packageVersion }
          $version = $version.TrimStart("v")

          echo "PACKAGE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
        working-directory: ./
        shell: pwsh
      - run: npx lerna publish '$env:PACKAGE_VERSION' --no-git-tag-version --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}